### ISSUE TITLE
Install ArgoCD via new 4.7 OpenShift GitOps Operator

### ISSUE THREAD

**Issue by csantanapr** [cloud-native-toolkit/planning#742]
Carlos want to install ArgoCD with the Toolkit but install it using OpenShift GitOps Operator on clusters 4.7+ this way getting enterprise support via Red Hat entitlements/subscription of OpenShift

**Comment by csantanapr** [comment]
When using the OpenShift operator ArgoCD is not installed in the “tools” by default we should make sure toolkit docs and gitops templates make a note of this, also app launcher will be added by the operator not longer the toolkit.

**Comment by csantanapr** [comment]
There is not much documentation on the operator than install the operator and access ArgoCD UI https://docs.openshift.com/container-platform/4.7/cicd/gitops/getting-started-with-openshift-gitops.html

there is going to be a CLI integration but is not documented yet

**Comment by seansund** [comment]
We can start to prepare for GitOps Operator now by deploying the operator in a namespace other than `tools`

**Comment by csantanapr** [comment]
I installed OCP 4.7 on VMware, and by "I installed" I mean I click a button and got a cluster 😂 

Here is the OpenShift GitOps Operator on Operator Hub

Components
- Argo CD 1.8.4
- GitOps Application Manager CLI 0.0.21 https://github.com/redhat-developer/kam/releases/tag/v0.0.21

Default Instance CR
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  server:
    route:
      enabled: true
```


![image](https://user-images.githubusercontent.com/1094878/109874088-a6029080-7c3c-11eb-9552-94c78ffdb1d2.png)

**Comment by mjperrins** [comment]
This is nice, was this VMWare on IBM ?

**Comment by csantanapr** [comment]
>This is nice, was this VMWare on IBM ?

in IBM servers running in DTE Infra.

**Comment by lsteck** [comment]
Installed the Cloud-Native Toolkit via the quick install and `oc credentials` returns the proper credentials for ArgoCD.
