### ISSUE TITLE
Quarkus starter kit tile points to an empty, archived repo

### ISSUE THREAD

**Issue by bwoolf1** [cloud-native-toolkit/planning#804]
Why does the Toolkit have a tile for a Quarkus Microservice? The repo is empty and has been archived. The tile should be linked to the right repo or should be removed.

There's a Starter Kit tile in the Developer Dashboard labeled Quarkus Microservice. It links to the template repo https://github.com/cloud-native-toolkit/template-quarkus. That repo only has a readme file and GitHub says "This repository has been archived by the owner. It is now read-only."

**Comment by bwoolf1** [comment]
@lsteck: Looks like you archived https://github.com/cloud-native-toolkit/template-quarkus. Should the tile link to https://github.com/ibm/template-quarkus?

**Comment by bwoolf1** [comment]
Looks like [ibm/template-quarkus](https://github.com/ibm/template-quarkus) should have a `pipeline.yaml` file that specifies `ibm-java-maven`.

**Comment by lsteck** [comment]
@bwoolf1 Where do you see the link to the Quarkus starter kit that points to [https://github.com/cloud-native-toolkit/template-quarkus](https://github.com/cloud-native-toolkit/template-quarkus)?

I updated the developer dashboard on Feb 26th with this [commit](https://github.com/cloud-native-toolkit/developer-dashboard/commit/82d87944b667260e6e963b90892a5ceb960f723e#diff-ca5f4f6cbe9b76c6b252119c4948c0e8af6fb51317a877d12c4cc14e94f8cb2a)

Is it possible the developer dashboard you found with the old link was created before then?
