### ISSUE TITLE
Replace GOGs installation with Gitea

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/planning#860]

**Comment by lsteck** [comment]
Create a Teraaform module to install Gitea using this operator https://github.com/redhat-gpte-devopsautomation/gitea-operator

**Comment by lsteck** [comment]
I wonder if we should be using this one instead.  It is by folks at RedHat and it uses images from Quay.
https://github.com/redhat-gpte-devopsautomation/gitea-operator

**Comment by lsteck** [comment]
Issue with the GPTE operator is it pulls an image from `registry.redhat.io` that relies on a pull secret installed with OCP that will not be available on IKS.

https://github.com/redhat-gpte-devopsautomation/gitea-operator/blob/master/config/default/manager_auth_proxy_patch.yaml
